version: '3'

services:
  app:
    build: '.'
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - DB_TYPE=${DB_TYPE}
    - DB_HOST=${DB_HOST_DOCKER}
    - CACHE_PORT=${CACHE_PORT}
    - CACHE_PASSWORD=${CACHE_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "cache"
    command: ["./scripts/wait-for-postgres.sh", "http://localhost:5432"]

  db:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}

  cache:
    image: redis
    ports:
      - ${CACHE_PORT}:${CACHE_PORT}
