version: '3'

services:
  app:
    build: '.'
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_DB=anti-fraud-api
    - POSTGRES_USER=postgres
    - db_type=postgres
    # - db_host=localhost
    - db_host=host.docker.internal

    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "cache"
  db:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_DB=anti-fraud-api
    ports:
      - 5432:5432
  cache:
    image: redis
    ports:
      - 6379:6379
