version: '3'

services:
  app:
    build: '.'
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - DB_TYPE=${DB_TYPE}
    - DB_HOST=${DB_HOST_DOCKER}
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "cache"
    command: ["./scripts/wait-for-postgres.sh", "http://db:${DB_PORT}"]

  db:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  cache:
    image: redis
    ports:
      - 6379:6379
